exclude = [
    "projects/owa-env-desktop/scripts",
    "projects/owa-env-gst/owa_env_gst/gst-plugins/python/py_utctimestampsrc.py",
    "projects/owa-env-gst/scripts",
    "poc",
]

line-length = 119

[lint.isort]
known-first-party = [
    "mcap_owa",
    "owa",
    "owa_env_desktop",
    "owa_env_gst",
    "owa_game_agent",
]