[project]
name = "video-decoding-server"
version = "0.1.0"
description = "High-performance video decoding server using NVIDIA Triton Inference Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "av>=15.0",
    "loguru",
    "numpy>=2.0",
    "opencv-python-headless",
    "pillow>=9.4.0",
]
