# OWA Project Dev Image - Complete Development Environment
ARG BASE_DEV_IMAGE=owa/base:dev
FROM ${BASE_DEV_IMAGE}

# Project setup arguments
ARG PROJECT_DIR=/workspace
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000
ARG CONDA_INSTALL_PATH=/opt/conda

# Set working directory
WORKDIR ${PROJECT_DIR}

# Copy and run project setup script
COPY --chown=${USERNAME}:${USERNAME} ./setup_project.sh /tmp/setup_project.sh
RUN --mount=type=cache,target=/home/${USERNAME}/.cache/pip,sharing=locked,uid=${USER_UID},gid=${USER_GID} \
    --mount=type=cache,target=/home/${USERNAME}/.cache/uv,sharing=locked,uid=${USER_UID},gid=${USER_GID} \
    --mount=type=cache,target=${CONDA_INSTALL_PATH}/pkgs,sharing=locked,uid=${USER_UID},gid=${USER_GID} \
    chmod +x /tmp/setup_project.sh && \
    /tmp/setup_project.sh ${PROJECT_DIR} && \
    rm /tmp/setup_project.sh

# Default configuration
SHELL ["/bin/zsh", "-c"]
CMD ["/bin/zsh"]
