# docker-compose.yml
version: '3'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./agent:/app/agent
      - ./shared:/app/shared

  evaluator:
    build:
      context: .
      dockerfile: Dockerfile.evaluator
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
    volumes:
      - ./evaluator:/app/evaluator
      - ./shared:/app/shared