name: Pytest on Windows (common)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -el {0}

    env:
      PYTHONIOENCODING: utf-8 # https://github.com/Textualize/rich/issues/212
      PYTHONUTF8: 1 # from https://github.com/ndonkoHenri/flet-github-action-workflows/blob/main/.github/workflows/windows-build.yml#L29C3-L29C16
      # below line is legacy line, but I'm keeping it here for reference to know where the packages are installed
      # GST_PLUGIN_PATH: "D:\\a\\open-world-agents\\open-world-agents\\projects\\owa-env-gst\\gst-plugins"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: ./.github/actions/setup-conda-env
        with:
          os: windows
          cache-number: '0'
          cache-suffix: 'pytest'

      - name: Setup uv Environment
        uses: ./.github/actions/setup-uv-env
        with:
          show-uv-cache-info: 'true'

      - name: Install dependencies
        run: vuv install --dev

      - name: Run pytest with coverage
        run: pytest --cov --cov-report=xml --cov-report=html --cov-report=term

      - name: Install owa-env-example
        run: vuv pip install -e projects/owa-env-example

      - name: Run pytest for owa-env-example with coverage
        run: pytest projects/owa-env-example/tests --cov=projects/owa-env-example --cov-append --cov-report=xml --cov-report=html --cov-report=term

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/