name: Pytest on Windows (common)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -el {0}

    env:
      PYTHONIOENCODING: utf-8 # https://github.com/Textualize/rich/issues/212
      PYTHONUTF8: 1 # from https://github.com/ndonkoHenri/flet-github-action-workflows/blob/main/.github/workflows/windows-build.yml#L29C3-L29C16
      # below line is legacy line, but I'm keeping it here for reference to know where the packages are installed
      # GST_PLUGIN_PATH: "D:\\a\\open-world-agents\\open-world-agents\\projects\\owa-env-gst\\gst-plugins"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: ./.github/actions/setup-conda-env
        with:
          os: windows
          cache-number: '0'
          cache-suffix: 'pytest'

      - name: Setup uv Environment
        uses: ./.github/actions/setup-uv-env
        with:
          show-uv-cache-info: 'true'

      - name: Install dependencies
        run: vuv install --dev

      - name: Debug encoding settings
        run: |
          python -c "
          import sys, locale
          print('sys.getfilesystemencoding():', sys.getfilesystemencoding())
          print('locale.getpreferredencoding(False):', locale.getpreferredencoding(False))
          print('sys.stdout.encoding:', sys.stdout.encoding)
          print('sys.stderr.encoding:', sys.stderr.encoding)
          print('sys.flags.utf8_mode:', sys.flags.utf8_mode)
          "

      - name: Run pytest
        run: pytest

      - name: Install owa-env-example
        run: vuv pip install -e projects/owa-env-example

      - name: Run pytest for owa-env-example
        run: pytest projects/owa-env-example/tests